events/urls.py
""" 'Events' URL Configuration
    - Configuration for the different event & vendor pages
"""

from django.conf.urls import url

from . import views

urlpatterns= [
    # Ex. /events/ -> default view of upcoming Off-The-Grid events
    url(r'^$', views.index, name='index'),
    # Ex. /events/vendors -> list of all vendors in descending occurrence count
    url(r'^vendors/$', views.vendors, name='vendors'),
    # Ex. /events/<event_name>/<event_date> -> specific event with its vendors
    url(r'^(?P<event_name>.*?)/(?P<event_date>[\d-]+?)$', views.details,
        name='details'),
    # Ex. /events/<vendor_name> -> specific vendor with its upcoming events
    url(r'^(?P<vendor_name>.*?)$', views.vendor, name='vendor'),
]

home/urls.py
""" 'Home' URL Configuration
    - Configuration for the default home page
"""

from django.conf.urls import url

from . import views

urlpatterns= [
    url(r'^$', views.index, name='index'),
]

offthegrid/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^events/', include('events.urls', namespace="events")),
    #url(r'^admin/', include('admin.site.urls')),
]

events/models.py
from django.db import models

# Create your models here.

class Vendor(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateField("Event date")
    start = models.TimeField("Event start time")
    end = models.TimeField("Event end time")
    location = models.CharField(max_length=200)

    class Meta:
        unique_together = ("name", "date")

    def __str__(self):
        return str(self.name + " --- " + self.date.isoformat() + 
                    " --- " + self.location)

class Event_Vendor(models.Model):
    event = models.ForeignKey(Event)
    vendor = models.ForeignKey(Vendor)

    class Meta:
        unique_together = ("event", "vendor")

    def __str__(self):
        return str(self.event) + " --- " + str(self.vendor)

home/models.py
from django.db import models

# Create your models here.

events/views.py
# 'Events' Views

from django.shortcuts import render, get_object_or_404

from .models import Event, Vendor, Event_Vendor
import datetime

# Default page - limits number of future events shown to 2 weeks
def index(request):
    future_marker = datetime.datetime.now() + datetime.timedelta(14)
    events_list = Event.objects.filter(date__lte=future_marker, \
                  date__gt=datetime.datetime.now()).order_by('date')
    context = {'events': events_list}

    return render(request, 'events/index.html', context)

# Event details page - shows the vendors at the given event
def details(request, event_name, event_date):
    e = Event.objects.filter(name=event_name, date=event_date)[0]

    ev_list = Event_Vendor.objects.filter(event=e)
    vendors = [ev.vendor for ev in ev_list]
    context = {'vendors': vendors, 'event': e}

    return render(request, 'events/details.html', context)

# Individual vendor page - shows past and future counts, along with events
def vendor(request, vendor_name, days=30):
    v = Vendor.objects.filter(name=vendor_name)[0]
    curr_marker = datetime.datetime.now()
    past_marker = curr_marker - datetime.timedelta(days)

    past_list = Event_Vendor.objects.filter(vendor=v, \
                event__date__lte=curr_marker, event__date__gte=past_marker) \
                .order_by('event__date').reverse()[:20]
    past_list = [p.event for p in past_list]

    future_list = Event_Vendor.objects.filter(vendor=v, \
                  event__date__gt=curr_marker).order_by('event__date')
    future_list = [f.event for f in future_list]

    context = {'name': vendor_name,
               'past_list': past_list, 'past_count': len(past_list),
               'future_list': future_list, 'future_count': len(future_list)}

    return render(request, 'events/vendor.html', context)

# All vendors page - displays them in order
def vendors(request, days=30):
    vendor_list = Vendor.objects.all()
    curr_marker = datetime.datetime.now()
    past_marker = curr_marker - datetime.timedelta(days)

    counts = {}

    for v in vendor_list:
        ev_list = Event_Vendor.objects.filter(vendor=v, \
                  event__date__lte=curr_marker, event__date__gte=past_marker)

        counts[v.name] = len(ev_list)

    vendors = []
    for k in sorted(counts, key=counts.get, reverse=True):
        vendors.append((k, counts[k]))

    return render(request, 'events/vendors.html', {'vendors': vendors})

home/views.py
# 'Home' Views

from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html')

events/templates/events/details.html
<!-- Specific Event's Details Page-->
<html>
    <head>
        <a href="{% url 'home:index' %}">
            OFF THE GRID
        </a>
    </head>
    {% autoescape off %}
    <body>
    {% if event %}
        <h1>{{ event.name }}</h1>
        <h2>{{ event.date }}</h2>
        <h2>{{ event.location }}</h2>
        <h2>{{ event.start }} to {{ event.end }}</h2>
    {% endif %}
    {% if vendors %}
        <h2> Attending Vendors: </h2>
        <ul>
        {% for v in vendors %}
            <li><a href="{% url 'events:vendor' v.name %}">
                {{ v }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </body>
    {% endautoescape %}
</html>

events/templates/events/index.html
<!-- Events Page -->
<html>
    <head>
        <a href="{% url 'home:index' %}">
            OFF THE GRID
        </a>
    </head>
{% autoescape off %}
{% if events %}
    <body>
        <h2>Future Events:</h2>
        <ul>
        {% for event in events %}
            <li>
            <a href="{% url 'events:details' event.name event.date %}">
                {{ event }}
            </a>
            </li>
        {% endfor %}
        </ul>
    </body>
{% endif %}
{% endautoescape %}

</html>

events/templates/events/vendor.html
<!-- Individual Vendor's Page -->
<html>
    <head>
        <a href="{% url 'home:index' %}">
            OFF THE GRID
        </a>
    </head>
    {% autoescape off %}
    <body>
        <h1>
            {{ name }}
        </h1>
        <h3>
            Past # of occurrences: {{ past_count }}
        </h3>
    {% if past_list %}
        <h4>
            Past Events
        </h4>
        <ul>
        {% for p in past_list %}
            <li><a href="{% url 'events:details' p.name p.date %}">
                {{ p }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}

        <h3>
            Future # of occurrences: {{ future_count }}
        </h3>
    {% if future_list %}
        <h4>
            Future Events
        </h4>
        <ul>
        {% for f in future_list %}
            <li><a href="{% url 'events:details' f.name f.date %}">
                {{ f }}
            </li>
        {% endfor %}
        </ul>
    {% endif %}

    </body>
    {% endautoescape %}
</html>

events/templates/events/vendors.html
<!-- All Vendors Page -->
<html>
    <head>
        <a href="{% url 'home:index' %}">
            OFF THE GRID
        </a>
    </head>
    {% autoescape off %}
    <body>
        <h1> VENDORS </h1>
        
    {% if vendors %}
        <ul>
        {% for v in vendors %}
            <li>
                <a href="{% url 'events:vendor' v.0 %}">{{ v.0 }}</a>
                <div><strong>{{ v.1 }}</strong></div>
            </li>
        {% endfor %}
        </ul>
        <ul>
    {% endif %}
    </body>
    {% endautoescape %}
</html>

home/templates/home/index.html
<!-- Home Page -->
<html>
    <head>
        <a href="{% url 'home:index' %}">
            OFF THE GRID
        </a>
    </head>
    <body>
        <h1>
            <a href="{% url 'events:index' %}">EVENTS</a>
        </h1>

        <h1>
            <a href="{% url 'events:vendors' %}">VENDORS</a>
        </h1>
    </body>
</html>